version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - github_actions
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/"
    labels:
      - dependencies
      - terraform
    schedule:
      interval: "weekly"
